// go generate gen.go
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT

package stun

// Session Traversal Utilities for NAT (STUN) Parameters, STUN Methods, Updated: 2015-08-27
const (
	MethodBinding           Method = 0x001 // Binding
	MethodAllocate          Method = 0x003 // Allocate
	MethodRefresh           Method = 0x004 // Refresh
	MethodSend              Method = 0x006 // Send
	MethodData              Method = 0x007 // Data
	MethodCreatePermission  Method = 0x008 // CreatePermission
	MethodChannelBind       Method = 0x009 // ChannelBind
	MethodConnect           Method = 0x00A // Connect
	MethodConnectionBind    Method = 0x00B // ConnectionBind
	MethodConnectionAttempt Method = 0x00C // ConnectionAttempt
)

var methods = map[Method]string{
	0x001: "binding",
	0x003: "allocate",
	0x004: "refresh",
	0x006: "send",
	0x007: "data",
	0x008: "create permission",
	0x009: "channel bind",
	0x00A: "connect",
	0x00B: "connection bind",
	0x00C: "connection attempt",
}

// Session Traversal Utilities for NAT (STUN) Parameters, STUN Attributes, Updated: 2015-08-27
const (
	attrMAPPED_ADDRESS            = 0x0001 // MAPPED-ADDRESS
	attrCHANGE_REQUEST            = 0x0003 // CHANGE-REQUEST
	attrUSERNAME                  = 0x0006 // USERNAME
	attrMESSAGE_INTEGRITY         = 0x0008 // MESSAGE-INTEGRITY
	attrERROR_CODE                = 0x0009 // ERROR-CODE
	attrUNKNOWN_ATTRIBUTES        = 0x000A // UNKNOWN-ATTRIBUTES
	attrCHANNEL_NUMBER            = 0x000C // CHANNEL-NUMBER
	attrLIFETIME                  = 0x000D // LIFETIME
	attrXOR_PEER_ADDRESS          = 0x0012 // XOR-PEER-ADDRESS
	attrDATA                      = 0x0013 // DATA
	attrREALM                     = 0x0014 // REALM
	attrNONCE                     = 0x0015 // NONCE
	attrXOR_RELAYED_ADDRESS       = 0x0016 // XOR-RELAYED-ADDRESS
	attrREQUESTED_ADDRESS_FAMILY  = 0x0017 // REQUESTED-ADDRESS-FAMILY
	attrEVEN_PORT                 = 0x0018 // EVEN-PORT
	attrREQUESTED_TRANSPORT       = 0x0019 // REQUESTED-TRANSPORT
	attrDONT_FRAGMENT             = 0x001A // DONT-FRAGMENT
	attrACCESS_TOKEN              = 0x001B // ACCESS-TOKEN
	attrXOR_MAPPED_ADDRESS        = 0x0020 // XOR-MAPPED-ADDRESS
	attrRESERVATION_TOKEN         = 0x0022 // RESERVATION-TOKEN
	attrPRIORITY                  = 0x0024 // PRIORITY
	attrUSE_CANDIDATE             = 0x0025 // USE-CANDIDATE
	attrPADDING                   = 0x0026 // PADDING
	attrRESPONSE_PORT             = 0x0027 // RESPONSE-PORT
	attrCONNECTION_ID             = 0x002A // CONNECTION-ID
	attrSOFTWARE                  = 0x8022 // SOFTWARE
	attrALTERNATE_SERVER          = 0x8023 // ALTERNATE-SERVER
	attrCACHE_TIMEOUT             = 0x8027 // CACHE-TIMEOUT
	attrFINGERPRINT               = 0x8028 // FINGERPRINT
	attrICE_CONTROLLED            = 0x8029 // ICE-CONTROLLED
	attrICE_CONTROLLING           = 0x802A // ICE-CONTROLLING
	attrRESPONSE_ORIGIN           = 0x802B // RESPONSE-ORIGIN
	attrOTHER_ADDRESS             = 0x802C // OTHER-ADDRESS
	attrECN_CHECK_STUN            = 0x802D // ECN-CHECK STUN
	attrTHIRD_PARTY_AUTHORIZATION = 0x802E // THIRD-PARTY-AUTHORIZATION
	attrCISCO_STUN_FLOWDATA       = 0xC000 // CISCO-STUN-FLOWDATA
)

// Session Traversal Utilities for NAT (STUN) Parameters, STUN Error Codes, Updated: 2015-08-27
const (
	StatusTryAlternate                 = 300 // Try Alternate
	StatusBadRequest                   = 400 // Bad Request
	StatusUnauthorized                 = 401 // Unauthorized
	StatusForbidden                    = 403 // Forbidden
	StatusUnknownAttribute             = 420 // Unknown Attribute
	StatusAllocationMismatch           = 437 // Allocation Mismatch
	StatusStaleNonce                   = 438 // Stale Nonce
	StatusAddressFamilynotSupported    = 440 // Address Family not Supported
	StatusWrongCredentials             = 441 // Wrong Credentials
	StatusUnsupportedTransportProtocol = 442 // Unsupported Transport Protocol
	StatusPeerAddressFamilyMismatch    = 443 // Peer Address Family Mismatch
	StatusConnectionAlreadyExists      = 446 // Connection Already Exists
	StatusConnectionTimeoutorFailure   = 447 // Connection Timeout or Failure
	StatusAllocationQuotaReached       = 486 // Allocation Quota Reached
	StatusRoleConflict                 = 487 // Role Conflict
	StatusServerError                  = 500 // Server Error
	StatusInsufficientCapacity         = 508 // Insufficient Capacity
)
